
export const LOGOUT = 'LOGOUT';
export const LOGIN_COMPLETED = 'LOGIN_COMPLETED';
export const SIGNUP_COMPLETED = 'SIGNUP_COMPLETED';
export const HIDE_ANIMATED_OVERLAY = 'HIDE_ANIMATED_OVERLAY';
export const SHOW_ANIMATED_OVERLAY = 'SHOW_ANIMATED_OVERLAY';
export const COMPLETE_ANIMATION_ANIMATED_OVERLAY = 'COMPLETE_ANIMATION_ANIMATED_OVERLAY';